# Generated by Django 2.0.4 on 2018-04-30 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isbn', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('author', models.TextField()),
                ('year', models.CharField(max_length=255)),
            ],
        ),
    ]
