# Generated by Django 2.0.4 on 2018-05-05 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20180505_1710'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pizza',
            name='type',
        ),
    ]
