# Generated by Django 2.0.4 on 2018-05-08 11:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0006_pizzasize'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('orders', '0004_pizzaname_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('price', models.FloatField(null='false')),
                ('status', models.IntegerField(choices=[(1, 'pending'), (2, 'ready')], default=1)),
                ('customer', models.ForeignKey(null='false', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PizzaOrders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(max_length=255)),
                ('topping', models.CharField(max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name='pizza',
            name='name',
        ),
        migrations.RemoveField(
            model_name='pizza',
            name='price',
        ),
        migrations.RemoveField(
            model_name='pizzaname',
            name='type',
        ),
        migrations.DeleteModel(
            name='Pizza',
        ),
        migrations.DeleteModel(
            name='PizzaName',
        ),
        migrations.DeleteModel(
            name='PizzaPrice',
        ),
        migrations.DeleteModel(
            name='PizzaType',
        ),
        migrations.AddField(
            model_name='pizzaorders',
            name='name',
            field=models.ForeignKey(null='false', on_delete=django.db.models.deletion.CASCADE, to='menu.PizzaName'),
        ),
        migrations.AddField(
            model_name='pizzaorders',
            name='type',
            field=models.ForeignKey(null='false', on_delete=django.db.models.deletion.CASCADE, to='menu.PizzaType'),
        ),
    ]
