# Generated by Django 2.0.4 on 2018-05-08 11:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0006_pizzasize'),
        ('orders', '0005_auto_20180508_1846'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='size',
            field=models.ForeignKey(null='false', on_delete=django.db.models.deletion.CASCADE, to='menu.PizzaSize'),
        ),
    ]
