# Generated by Django 2.0.4 on 2018-05-08 12:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_order_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='size',
            field=models.ForeignKey(null='true', on_delete=django.db.models.deletion.CASCADE, to='menu.PizzaSize'),
        ),
    ]
