# Generated by Django 2.0.4 on 2018-05-01 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_id', models.BigIntegerField()),
                ('user_id', models.BigIntegerField()),
                ('length', models.BigIntegerField()),
            ],
        ),
    ]
