# Generated by Django 2.0.4 on 2018-05-06 07:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_pizzatopping'),
    ]

    operations = [
        migrations.AddField(
            model_name='pizzaname',
            name='price',
            field=models.ForeignKey(null='false', on_delete=django.db.models.deletion.CASCADE, to='menu.PizzaPrice'),
        ),
    ]
