# Generated by Django 2.0.4 on 2018-05-06 08:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0004_pizzaname_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pizza',
            name='price',
        ),
        migrations.RemoveField(
            model_name='pizzaname',
            name='price',
        ),
        migrations.RemoveField(
            model_name='pizzaname',
            name='type',
        ),
        migrations.AddField(
            model_name='pizza',
            name='l_price',
            field=models.FloatField(null='false'),
        ),
        migrations.AddField(
            model_name='pizza',
            name='s_price',
            field=models.FloatField(null='false'),
        ),
        migrations.AddField(
            model_name='pizza',
            name='type',
            field=models.ForeignKey(null='false', on_delete=django.db.models.deletion.CASCADE, to='menu.PizzaType'),
        ),
        migrations.DeleteModel(
            name='PizzaPrice',
        ),
    ]
