# Generated by Django 2.0.4 on 2018-05-08 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0007_dinnerplatters_pasta_salads_subs'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dinnerplatters',
            old_name='price',
            new_name='l_price',
        ),
        migrations.RenameField(
            model_name='subs',
            old_name='price',
            new_name='l_price',
        ),
        migrations.AddField(
            model_name='dinnerplatters',
            name='s_price',
            field=models.FloatField(null='false'),
        ),
        migrations.AddField(
            model_name='subs',
            name='s_price',
            field=models.FloatField(null='false'),
        ),
    ]
