# Generated by Django 2.0.4 on 2018-05-08 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0008_auto_20180508_1943'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dinnerplatters',
            name='size',
        ),
        migrations.RemoveField(
            model_name='subs',
            name='size',
        ),
    ]
